#!/usr/bin/env ruby

require 'date'

POSTS_DIR = '_posts/'

post = ARGV[0]

File.open(POSTS_DIR + Date.today.strftime("%Y-%m-%d-") + post + '.md', 'w') {|f| f.write(
  "---\nlayout: post\nsection-type: post\n\n\n#date: yyyy-mm-dd\n#update-text: ""\n#lastmod: yyyy-mm-dd\n\ntitle: \"Title\"\nimage: \"path/to/image\"\ntop-image: \"/path/to/bannerimage\"\nslug: \"a-blog-post\"\ncategory: \"category\"\ntags: [ 'tag1', 'tag2' ]\n\npostdescription: description of post for site\n\ntitletag: <meta> title tag\ndescription: <meta> description\n---")
}

puts('[+] Created ' + post + ' post')
